;;; Automatically generated by ‘recentf’ on Wed May 13 00:51:07 2026.

(setq recentf-list
      '(
        "~/.config/emacs/README.org"
        "~/.config/emacs/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
